[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
dapp = "C6N3BUnwxmCQC1i9RtHryEktQYJG9Q5bAAndJV6BJ92a"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/workspaces/sbc-workspace/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
